# Generated by Django 4.1.7 on 2023-03-19 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_ordermodel_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_text', models.CharField(blank=True, max_length=255, verbose_name='№ Чека')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.ordermodel', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Транзакция оплаты',
                'verbose_name_plural': 'Транзакции оплаты',
                'ordering': ('-created_at',),
            },
        ),
    ]
