# Generated by Django 4.1.7 on 2023-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransactionmodel',
            name='verification_text',
        ),
        migrations.AddField(
            model_name='paymenttransactionmodel',
            name='data',
            field=models.JSONField(default={'unknown': 'unknown'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransactionmodel',
            name='operation_type',
            field=models.CharField(default='unknown', max_length=256, verbose_name='Тип операции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransactionmodel',
            name='payment_id',
            field=models.CharField(default='unknown', max_length=128, verbose_name='Идентификатор оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransactionmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Произведена'), ('incompleted', 'Не произведена')], default='not completed', max_length=11),
        ),
        migrations.AddField(
            model_name='paymenttransactionmodel',
            name='value',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=6, verbose_name='Оплачено'),
            preserve_default=False,
        ),
    ]
