# Generated by Django 4.1.7 on 2023-03-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_paymenttransactionmodel_verification_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactionmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'Произведена'), ('incompleted', 'Не произведена'), ('declined', 'Отклонена')], default='not completed', max_length=11),
        ),
    ]
