# Generated by Django 4.1.7 on 2023-03-13 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productcategorymodel_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_auto_20230307_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'ordering': ('-created_at',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Открыта'), ('c', 'Закрыта'), ('f', 'Заморожена')], default='o', max_length=1),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartmodel', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.productmodel', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Принадлежит'),
        ),
    ]
