# Generated by Django 4.1.7 on 2023-03-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_cartmodel_options_cartmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новая'), ('o', 'Заказана'), ('d', 'Удалена')], default='n', max_length=1),
        ),
    ]
