# Generated by Django 4.1.7 on 2023-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Доступен'), ('n', 'Недоступен'), ('d', 'Удалён')], default='a', max_length=1),
        ),
    ]
