# Generated by Django 4.1.7 on 2023-03-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cartitemmodel_status_alter_cartmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('not available', 'Недоступна'), ('ordered', 'Заказана'), ('deleted', 'Удалена')], default='new', max_length=13),
        ),
    ]
