# Generated by Django 3.2.18 on 2023-03-01 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproductsmodel',
            options={'verbose_name': 'OrderProduct'},
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user email'),
        ),
        migrations.AlterField(
            model_name='orderproductsmodel',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.productmodel', verbose_name='product title'),
        ),
    ]
