# Generated by Django 4.1.7 on 2023-03-17 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderproductsmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductsmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.ordermodel', verbose_name='Заказ'),
        ),
    ]
