# Generated by Django 4.1.7 on 2023-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderproductsmodel_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='110.10', max_digits=7, verbose_name='К оплате'),
            preserve_default=False,
        ),
    ]
