# Generated by Django 4.1.7 on 2023-03-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordermodel_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новый'), ('paid', 'Оплачен'), ('sent', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменён')], default='new', max_length=9),
        ),
    ]
