# Generated by Django 4.1.7 on 2023-03-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductsmodel',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default='00.00', max_digits=6, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
