# Generated by Django 3.2.18 on 2023-03-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturemodel',
            name='product',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='product', to='products.picturemodel'),
            preserve_default=False,
        ),
    ]
