# Generated by Django 3.2.18 on 2023-03-07 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230307_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='picturemodel',
            name='product',
            field=models.ForeignKey(default='123e4567-e89b-12d3-a456-426614174000',
                                    on_delete=django.db.models.deletion.CASCADE, to='products.productmodel'),
            preserve_default=False,
        ),
    ]
