# Generated by Django 3.2.18 on 2023-03-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230307_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='characteristics',
            field=models.JSONField(default={'Char': 1}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel'),
        ),
    ]
