# Generated by Django 3.2.18 on 2023-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230308_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='characteristics',
            field=models.JSONField(null=True),
        ),
    ]
