# Generated by Django 3.2.18 on 2023-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productmodel_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='characteristics',
            field=models.JSONField(),
        ),
    ]
