# Generated by Django 3.2.18 on 2023-03-10 12:05

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productmodel_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='productcategorymodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='None', editable=False, populate_from='name', slugify=products.models.set_slugify),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='picture',
            field=models.ImageField(upload_to='products_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='picturemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productmodel', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productcategorymodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategorymodel', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='general_quantity',
            field=models.IntegerField(verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=82, verbose_name='Товар'),
        ),
    ]
