# Generated by Django 3.2.18 on 2023-03-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20230310_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='parameter',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='parameter',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='products', to='products.parametermodel', verbose_name='Параметры'),
            preserve_default=False,
        ),
    ]
