# Generated by Django 3.2.18 on 2023-03-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20230310_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='parameter',
        ),
        migrations.AddField(
            model_name='parametermodel',
            name='product',
            field=models.ForeignKey(default='123e4567-e89b-12d3-a456-426614174000', on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='products.productmodel', verbose_name='Параметры'),
            preserve_default=False,
        ),
    ]
