# Generated by Django 3.2.18 on 2023-03-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20230310_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
