# Generated by Django 3.2.18 on 2023-03-10 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productcategorymodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
