# Generated by Django 4.1.7 on 2023-03-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_productcategorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturemodel',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
    ]
