# Generated by Django 4.1.7 on 2023-03-27 09:55

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0025_alter_picturemodel_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymodel',
            name='user',
            field=models.ForeignKey(default='00673639-98a2-4380-9234-8deaa6f07653', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='productcategories', to=settings.AUTH_USER_MODEL, verbose_name='Добавлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='user',
            field=models.ForeignKey(default='00673639-98a2-4380-9234-8deaa6f07653', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Добавлен'),
            preserve_default=False,
        ),
    ]
